[tool.poetry]
name = "pipeline-api"
version = "0.1.0"
description = ""
authors = ["laolmstead <laolmstead19@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
